export interface PersonnelRecord {
  empId: string;
  name: string;
  department: string;
  organization: string;
  clName: string;
  email: string;
  position: string;
  scope: string;
}

export const mockPersonnel: PersonnelRecord[] = [
  {
    empId: 'EMP0001',
    name: 'Alex Tran',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'alex.tran@example.test',
    position: 'Quality Engineer',
    scope: 'Component Inspection',
  },
  {
    empId: 'EMP0002',
    name: 'Jamie Nguyen',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'jamie.nguyen@example.test',
    position: 'Lab Engineer',
    scope: 'Reliability Testing',
  },
  {
    empId: 'EMP0003',
    name: 'Taylor Pham',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'taylor.pham@example.test',
    position: 'Supplier Quality Engineer',
    scope: 'Supplier Audits',
  },
  {
    empId: 'EMP0004',
    name: 'Morgan Le',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'morgan.le@example.test',
    position: 'Component Engineer',
    scope: 'Part Qualification',
  },
  {
    empId: 'EMP0005',
    name: 'Jordan Ho',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'jordan.ho@example.test',
    position: 'Quality Specialist',
    scope: 'Process Monitoring',
  },
  {
    empId: 'EMP0006',
    name: 'Casey Vu',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'casey.vu@example.test',
    position: 'Quality Inspector',
    scope: 'Incoming Inspection',
  },
  {
    empId: 'EMP0007',
    name: 'Riley Do',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'riley.do@example.test',
    position: 'Test Engineer',
    scope: 'Environmental Testing',
  },
  {
    empId: 'EMP0008',
    name: 'Avery Bui',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'avery.bui@example.test',
    position: 'Supplier Analyst',
    scope: 'Supplier Performance',
  },
  {
    empId: 'EMP0009',
    name: 'Cameron Dang',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'cameron.dang@example.test',
    position: 'Technical Engineer',
    scope: 'Failure Analysis',
  },
  {
    empId: 'EMP0010',
    name: 'Parker Truong',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'parker.truong@example.test',
    position: 'Process Engineer',
    scope: 'Quality Control',
  },
  {
    empId: 'EMP0011',
    name: 'Quinn Vo',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'quinn.vo@example.test',
    position: 'Senior Quality Engineer',
    scope: 'Inspection Planning',
  },
  {
    empId: 'EMP0012',
    name: 'Reese Dao',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'reese.dao@example.test',
    position: 'Reliability Engineer',
    scope: 'Life Cycle Testing',
  },
  {
    empId: 'EMP0013',
    name: 'Skyler Cao',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'skyler.cao@example.test',
    position: 'Quality Coordinator',
    scope: 'Corrective Actions',
  },
  {
    empId: 'EMP0014',
    name: 'Rowan Ly',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'rowan.ly@example.test',
    position: 'Design Quality Engineer',
    scope: 'Design Validation',
  },
  {
    empId: 'EMP0015',
    name: 'Emerson Huynh',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'emerson.huynh@example.test',
    position: 'Manufacturing Engineer',
    scope: 'Line Quality',
  },
  {
    empId: 'EMP0016',
    name: 'Dakota Ngo',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'dakota.ngo@example.test',
    position: 'Quality Technician',
    scope: 'Material Verification',
  },
  {
    empId: 'EMP0017',
    name: 'Hayden Dinh',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'hayden.dinh@example.test',
    position: 'Validation Engineer',
    scope: 'Mechanical Testing',
  },
  {
    empId: 'EMP0018',
    name: 'Finley Lam',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'finley.lam@example.test',
    position: 'Supplier Engineer',
    scope: 'Supplier Qualification',
  },
  {
    empId: 'EMP0019',
    name: 'Sage Phan',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'sage.phan@example.test',
    position: 'Component Specialist',
    scope: 'Specification Review',
  },
  {
    empId: 'EMP0020',
    name: 'Blake Mai',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'blake.mai@example.test',
    position: 'Quality Engineer',
    scope: 'Process Audit',
  },
  {
    empId: 'EMP0021',
    name: 'Harper Vuong',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'harper.vuong@example.test',
    position: 'Inspection Engineer',
    scope: 'Sampling Inspection',
  },
  {
    empId: 'EMP0022',
    name: 'Kendall Chau',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'kendall.chau@example.test',
    position: 'Lab Specialist',
    scope: 'Thermal Testing',
  },
  {
    empId: 'EMP0023',
    name: 'Logan Ta',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'logan.ta@example.test',
    position: 'Supplier Quality Analyst',
    scope: 'Supplier Metrics',
  },
  {
    empId: 'EMP0024',
    name: 'Drew Kieu',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'drew.kieu@example.test',
    position: 'Materials Engineer',
    scope: 'Material Analysis',
  },
  {
    empId: 'EMP0025',
    name: 'Robin Ngo',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'robin.ngo@example.test',
    position: 'Quality Supervisor',
    scope: 'Production Support',
  },
  {
    empId: 'EMP0026',
    name: 'Shawn Lu',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'shawn.lu@example.test',
    position: 'Incoming Quality Engineer',
    scope: 'Supplier Materials',
  },
  {
    empId: 'EMP0027',
    name: 'Micah Ha',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'micah.ha@example.test',
    position: 'Reliability Technician',
    scope: 'Test Execution',
  },
  {
    empId: 'EMP0028',
    name: 'Ellis Tong',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'ellis.tong@example.test',
    position: 'Supplier Development Engineer',
    scope: 'Supplier Improvement',
  },
  {
    empId: 'EMP0029',
    name: 'Charlie Dam',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'charlie.dam@example.test',
    position: 'Component Validation Engineer',
    scope: 'Component Validation',
  },
  {
    empId: 'EMP0030',
    name: 'Sam Ninh',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'sam.ninh@example.test',
    position: 'Production Quality Engineer',
    scope: 'Manufacturing Compliance',
  },
];