export type PersonnelStatus = 'Active' | 'Inactive';

export interface PersonnelRecord {
  empId: string;
  name: string;
  department: string;
  organization: string;
  clName: string;
  email: string;
  position: string;
  scope: string;
  status: PersonnelStatus;
  preferredName?: string;
}

export const mockPersonnel: ReadonlyArray<PersonnelRecord> = [
  {
    empId: 'SYN-0001',
    name: 'Alex Tran',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'alex.tran@example.invalid',
    position: 'Quality Engineer',
    scope: 'Component Inspection',
    status: 'Active',
  },
  {
    empId: 'SYN-0002',
    name: 'Jamie Nguyen',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'jamie.nguyen@example.invalid',
    position: 'Lab Engineer',
    scope: 'Reliability Testing',
    status: 'Active',
  },
  {
    empId: 'SYN-0003',
    name: 'Taylor Pham',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'taylor.pham@example.invalid',
    position: 'Supplier Quality Engineer',
    scope: 'Supplier Audits',
    status: 'Active',
  },
  {
    empId: 'SYN-0004',
    name: 'Morgan Le',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'morgan.le@example.invalid',
    position: 'Component Engineer',
    scope: 'Part Qualification',
    status: 'Active',
  },
  {
    empId: 'SYN-0005',
    name: 'Jordan Ho',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'jordan.ho@example.invalid',
    position: 'Quality Specialist',
    scope: 'Process Monitoring',
    status: 'Active',
  },
  {
    empId: 'SYN-0006',
    name: 'Casey Vu',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'casey.vu@example.invalid',
    position: 'Quality Inspector',
    scope: 'Incoming Inspection',
    status: 'Active',
  },
  {
    empId: 'SYN-0007',
    name: 'Riley Do',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'riley.do@example.invalid',
    position: 'Test Engineer',
    scope: 'Environmental Testing',
    status: 'Inactive',
  },
  {
    empId: 'SYN-0008',
    name: 'Avery Bui',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'avery.bui@example.invalid',
    position: 'Supplier Analyst',
    scope: 'Supplier Performance',
    status: 'Active',
  },
  {
    empId: 'SYN-0009',
    name: 'Cameron Dang',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'cameron.dang@example.invalid',
    position: 'Technical Engineer',
    scope: 'Failure Analysis',
    status: 'Active',
  },
  {
    empId: 'SYN-0010',
    name: 'Parker Truong',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'parker.truong@example.invalid',
    position: 'Process Engineer',
    scope: 'Quality Control',
    status: 'Active',
  },
  {
    empId: 'SYN-0011',
    name: 'Quinn Vo',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'quinn.vo@example.invalid',
    position: 'Senior Quality Engineer',
    scope: 'Inspection Planning',
    status: 'Active',
  },
  {
    empId: 'SYN-0012',
    name: 'Reese Dao',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'reese.dao@example.invalid',
    position: 'Reliability Engineer',
    scope: 'Life Cycle Testing',
    status: 'Active',
  },
  {
    empId: 'SYN-0013',
    name: 'Skyler Cao',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'skyler.cao@example.invalid',
    position: 'Quality Coordinator',
    scope: 'Corrective Actions',
    status: 'Inactive',
  },
  {
    empId: 'SYN-0014',
    name: 'Rowan Ly',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'rowan.ly@example.invalid',
    position: 'Design Quality Engineer',
    scope: 'Design Validation',
    status: 'Active',
  },
  {
    empId: 'SYN-0015',
    name: 'Emerson Huynh',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'emerson.huynh@example.invalid',
    position: 'Manufacturing Engineer',
    scope: 'Line Quality',
    status: 'Active',
  },
  {
    empId: 'SYN-0016',
    name: 'Dakota Ngo',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'dakota.ngo@example.invalid',
    position: 'Quality Technician',
    scope: 'Material Verification',
    status: 'Active',
  },
  {
    empId: 'SYN-0017',
    name: 'Hayden Dinh',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'hayden.dinh@example.invalid',
    position: 'Validation Engineer',
    scope: 'Mechanical Testing',
    status: 'Active',
  },
  {
    empId: 'SYN-0018',
    name: 'Finley Lam',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'finley.lam@example.invalid',
    position: 'Supplier Engineer',
    scope: 'Supplier Qualification',
    status: 'Active',
  },
  {
    empId: 'SYN-0019',
    name: 'Sage Phan',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'sage.phan@example.invalid',
    position: 'Component Specialist',
    scope: 'Specification Review',
    status: 'Inactive',
  },
  {
    empId: 'SYN-0020',
    name: 'Blake Mai',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'blake.mai@example.invalid',
    position: 'Quality Engineer',
    scope: 'Process Audit',
    status: 'Active',
  },
  {
    empId: 'SYN-0021',
    name: 'Harper Vuong',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'harper.vuong@example.invalid',
    position: 'Inspection Engineer',
    scope: 'Sampling Inspection',
    status: 'Active',
  },
  {
    empId: 'SYN-0022',
    name: 'Kendall Chau',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'kendall.chau@example.invalid',
    position: 'Lab Specialist',
    scope: 'Thermal Testing',
    status: 'Active',
  },
  {
    empId: 'SYN-0023',
    name: 'Logan Ta',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'logan.ta@example.invalid',
    position: 'Supplier Quality Analyst',
    scope: 'Supplier Metrics',
    status: 'Active',
  },
  {
    empId: 'SYN-0024',
    name: 'Drew Kieu',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'drew.kieu@example.invalid',
    position: 'Materials Engineer',
    scope: 'Material Analysis',
    status: 'Active',
  },
  {
    empId: 'SYN-0025',
    name: 'Robin Ngo',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'robin.ngo@example.invalid',
    position: 'Quality Supervisor',
    scope: 'Production Support',
    status: 'Inactive',
  },
  {
    empId: 'SYN-0026',
    name: 'Nguyá»…n An NhiÃªn',
    preferredName: 'NhiÃªn',
    department: 'Incoming Quality',
    organization: 'IQC',
    clName: 'IQC Operations',
    email: 'nguyen.an.nhien@example.invalid',
    position: 'Incoming Quality Engineer',
    scope: 'Supplier Materials',
    status: 'Active',
  },
  {
    empId: 'SYN-0027',
    name: 'Tráº§n Minh Khoa',
    department: 'Reliability Lab',
    organization: 'QA',
    clName: 'Reliability Engineering',
    email: 'tran.minh.khoa@example.invalid',
    position: 'Reliability Technician',
    scope: 'Test Execution',
    status: 'Active',
  },
  {
    empId: 'SYN-0028',
    name: 'ê¹€í•˜ëŠ˜',
    department: 'Supplier Quality',
    organization: 'SCM',
    clName: 'Supplier Development',
    email: 'kim.haneul@example.invalid',
    position: 'Supplier Development Engineer',
    scope: 'Supplier Improvement',
    status: 'Active',
  },
  {
    empId: 'SYN-0029',
    name: 'ë°•ì„œì¤€',
    department: 'Component Engineering',
    organization: 'IQC',
    clName: 'Component Quality',
    email: 'park.seojun@example.invalid',
    position: 'Component Validation Engineer',
    scope: 'Component Validation',
    status: 'Active',
  },
  {
    empId: 'SYN-0030',
    name: 'LÃª Gia HÃ¢n',
    preferredName: 'HÃ¢n',
    department: 'Production Quality',
    organization: 'QA',
    clName: 'Manufacturing Quality',
    email: 'le.gia.han@example.invalid',
    position: 'Production Quality Engineer',
    scope: 'Manufacturing Compliance',
    status: 'Inactive',
  },
];