import { PermissionGate } from "@/components/portal/PermissionGate";
import { Activity, AlertTriangle, ArrowRight, CheckCircle2, Clock3, Download, FileWarning, Upload } from "lucide-react";
import Link from "next/link";
const metrics = [
 { label: "Pending Reviews", value: 3, note: "2 include warnings", icon: Clock3, tone: "warning" },
 { label: "Failed Imports", value: 1, note: "Last 7 days", icon: AlertTriangle, tone: "danger" },
 { label: "Completed Imports", value: 18, note: "Last 30 days", icon: CheckCircle2, tone: "success" },
 { label: "Validation Issues", value: 12, note: "4 blocking", icon: FileWarning, tone: "danger" },
 { label: "Downloads", value: 4, note: "2 published", icon: Download, tone: "neutral" },
];
const activity = ["IQC-SYN-1042 entered review", "IQC-SYN-1039 validation failed", "Release notes v0.1 published"];
export default function OverviewPage() { return <PermissionGate permission="dashboard.view"><div className="page-stack"><section className="page-heading"><div><p className="eyebrow">OPERATIONS SNAPSHOT</p><h2>Quality intake overview</h2><p>Work requiring attention across imports, validation, and controlled downloads.</p></div></section><div className="fixture-banner" role="note"><strong>Fixture provider</strong><span>All dashboard values are synthetic and isolated from production APIs.</span></div><section className="metric-grid" aria-label="Operational metrics">{metrics.map(metric => <article className="metric-panel" key={metric.label}><div className={`metric-icon ${metric.tone}`}><metric.icon /></div><div><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.note}</small></div></article>)}</section><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">RECENT ACTIVITY</p><h3>Operational events</h3></div><Link href="/audit">View audit <ArrowRight /></Link></div><ul className="activity-list">{activity.map((item, index) => <li key={item}><Activity /><span>{item}</span><time>{index + 1}h ago</time></li>)}</ul></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">QUICK ACTIONS</p><h3>Common destinations</h3></div></div><div className="quick-actions"><Link className="secondary-action" href="/imports"><Upload />Open Import Center</Link><Link className="secondary-action" href="/downloads"><Download />Open Download Center</Link></div><p className="muted compact-note">Import creation remains unavailable until its backend workflow is complete.</p></section></div></div></PermissionGate>; }